### PR TITLE
Adding capability to pass a host name with port and check if it's encrypted

### PR DESCRIPTION
**Pull request by lucasmedeirosleite**
With this pull request users can inform a different hostname with a different port and say if the url is encrypted

### CODE REVIEW

**Comment by soffes** [comment]
Thanks for your work on this. Can I ask why you need control over if it's encrypted or not.

I strongly recommend to always use an encrypted connection on mobile. If you don't, users that connect to Pusher on carriers that do transparent proxying (Verizon being the most notable in the US) will experience crashes in CFNetwork seemingly randomly. Switching to an encrypted connection prevents this.

**Comment by lucasmedeirosleite** [comment]
Oh no problem! I put an option on the construct method to say if it's encrypted or not (I was thinking on development environments, let me explain a little, I have a server which has the same api of pusher on my development environment, that's why I don't use an encrypted connection). I changed the default option to use a not encrypted connection, so this pull request could be accepted if I change back the default option to an encrypted connection?!

Thanks for the feedback :+1:

**Comment by soffes** [comment]
Added this [here](https://github.com/soffes/bully/commit/220a3531871e00b7a862fa61cad5cfbeebf06756)! I'm working on a few things in a branch that I'll merge soon. Thanks for your work!

**Comment by lucasmedeirosleite** [comment]
You're welcome! :+1:

**Pull request closed without merging**
