### PR TITLE
Added JSON parser error handler.

### PR DESCRIPTION
**Pull request by maddiesch**
When the parser returns and error and the handler block is set it is called passing in the NSError and the NSData.  The block should atempt to correclty parse the message data, and return it, or just return nil.

### CODE REVIEW

**Comment by soffes** [comment]
Interesting idea. I'm not sure how I feel about there being a global block. It might be better to have an optional parameter when subscribing to a channel.

**Comment by maddiesch** [comment]
I'll play with it over the weekend and ping you if I come up with anything.

**Comment by maddiesch** [comment]
Thought about it, liked it, changed it.  Actually works a whole lot better for my use case.

**Comment by soffes** [comment]
Sorry to nitpick, but you do you think you could make it BLYErrorBlock that just has an error parameter (in BLYClient.h) so it can be used for generic errors. Then in BLYChannel, add it as a property. Use an enum for error codes and the only one for now will be json parse error. Eventually, we can add authentication failed (for private channels) etc. Thoughts?

I really appreciate your work on this!

**Comment by maddiesch** [comment]
Left the declarations in BLYChannel.h because of the include pattern.  The enum also includes a `BLYErrorTypeUnknown`, not used now but could be useful in the future.

**Comment by maddiesch** [comment]
Changing username broke submodule stuff.

**Comment by soffes** [comment]
Thanks dude.

**Comment by maddiesch** [comment]
Thanks for the great Pusher Client.

**Comment by soffes** [comment]
Forked my SocketRocket to samsoffes so it will continue to work until people update. Didn't realize that one was in use. I should probably switch the official one again at some point.

**Comment by soffes** [comment]
@skylarsch glad you like it :D

**Pull request merged**
